VendistaProject.UI/Controllers/UIController.cs
using Microsoft.AspNetCore.Mvc;
using VendistaProject.UI.Services;
using VendistaProject.UI.Services.Interfaces;
using VendistaProject.UI.Helper;
using Microsoft.AspNetCore.Mvc.Rendering;
using VendistaProject.Dto.Models.Interfaces;
using VendistaProject.Dto.Models;

namespace VendistaProject.UI.Controllers
{
    public class UIController : Controller
    {
        protected BaseApiService service = new BaseApiService();
        protected BaseViewModel model;
        protected Builder builder;
        public UIController()
        {
            model = new BaseViewModel(service);
        }

        public IActionResult Index(string? value = null)
        {
            if (value != null)
                model.bodyCommand = model.command.items[int.Parse(value)];
            return View(model);
        }
        public IActionResult Error(string error)
        {
            return View(error);
        }
        [HttpPost]
        public async Task<IActionResult> SendDataDB(string userIdTerminals, string? lastcommand, string? param1, string? param2, string? param3)
        {
            try
            {
                if(lastcommand == null)
                    lastcommand = model.command.items[0].name;
                builder = new Builder(service);
                var command = builder.BuildMultyCommand(
                    service.GetCommand(Services.TypeAuth.Partner).Result.items.FirstOrDefault(name => name.name == lastcommand).id,
                    param1, param2, param3);

                var result =
                    await service.SendCommand(
                    Services.TypeAuth.Partner,
                    int.Parse(userIdTerminals),
                    command,
                    lastcommand
                    );
                if (result != null)
                {
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error");
            }
            return RedirectToAction("Error");
        }

    }
    public enum TypeAuth
    {
        Client,
        Partner
    }
    public class BaseViewModel
    {
        public IEnumerable<IHistoryModel> histories { get; set; }
        public Command command { get; set; }
        public BodyCommand bodyCommand { get; set; }
        public BaseViewModel(BaseApiService service)
        {

            histories = service.GetHistories().Result;
            command = service.GetCommand(Services.TypeAuth.Partner).Result;

        }
        public List<SelectListItem> GetDropList()
        {
            var list = new List<SelectListItem>();
            int index = 0;
            foreach (var item in command.items)
            {
                list.Add(new SelectListItem
                {
                    Text = item.name,
                    Value = index.ToString()
                });
                index++;
            }
            return list;
        }

    }
}

VendistaProject.UI/Views/UI/Index.cshtml
@model VendistaProject.UI.Controllers.BaseViewModel;

@{
    Layout = null;
    ViewBag.Title = "Vendista";
    List<SelectListItem> lst = Model.GetDropList(); 
}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title> 
    <script src="~/lib/jquery/dist/jquery.js"></script> 
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css"/>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/style.css"/>
    <link rel="stylesheet" href="~/css/content.css" />
    <link rel="stylesheet" href="~/css/table-style.css"/>
</head>
<body>
    <header>
        <div class="header">
            <div class="logo">
                <img style="height:55px;" class="navbar-brand" id="logo" src="https://p.vendista.ru/images/logo_header_2_2x.png" />

            </div>
            <div href="#" class="logo-text">Личный кабинет - Отправка команд на терминал</div>
            <div class="menu">

                <a href="#" class="menu-item"><img style="width:22px; height:22px;" src="https://p.vendista.ru/images/user.svg" alt="Alternate Text" />Партнёр</a>
                <a href="#" class="menu-item"><img style="width:22px; height:22px; margin-right:20px; margin-left:15px;" src="@Url.Content("/icons/exit.png")" alt="Alternate Text" /></a>
            </div>
        </div>
    </header> 
        <div class="sidebar">
            <a href="#"><img class="icon-bar" src="@Url.Content("~/icons/customers.png")" alt="Alternate Text" />Клиенты</a>
            <a href="#"><img class="icon-bar" src="@Url.Content("~/icons/users.png")" />Пользователи</a>
            <a href="#"><img class="icon-bar" src="@Url.Content("~/icons/terminal.png")" />Терминалы</a>
            <a href="#"><img class="icon-bar" src="@Url.Content("~/icons/bank.png")" />TID Банка</a>
            <a href="#"><img class="icon-bar" src="@Url.Content("~/icons/transition.png")" />Транзакции</a>
            <a href="#"><img class="icon-bar" src="@Url.Content("~/icons/log_terminals.png")" />Логи терминалов</a>
            <a href="#"><img class="icon-bar" src="@Url.Content("~/icons/cash.png")" />Кассы</a>
            <a href="#">
                <img class="icon-bar" src="@Url.Content("~/icons/log_terminals.png")" alt="Alternate Text" /> Привязать терминалы к клиенту списком
            </a>
        </div>
        <div class="content">
                
            @using (Html.BeginForm("Index", "UI", FormMethod.Post,new{@class="form"}))
            {

                <label class="form-label">Команда</label><br />
                @Html.DropDownList("value", lst, new { onchange = "this.form.submit()", @class="form-input" })
              
            } 
            @using (Html.BeginForm("SendDataDB", "UI", FormMethod.Post, new { @class="form"}))
            {

                <label class="form-label">ID Терминала(ов)</label>
                <textarea id="user-id-terminals" name="userIdTerminals" class="form-input">129</textarea>
                <div class="command-form">
                    @if (Model.bodyCommand != null)
                    {
                        <input id="lastcommand" name="lastcommand" value="@Model.bodyCommand.name" type="text" style="position:absolute; display:none" />

                        if (Model.bodyCommand.parameter_name1 != null)
                        {
                            <label for="param1" class="form-label">@Model.bodyCommand.parameter_name1</label>
                            <input name="param1" , id="param1" , placeholder="@Model.bodyCommand.parameter_default_value1" , type="text" />

                        }
                        if (Model.bodyCommand.parameter_name2 != null)
                        {
                            <label for="param2" class="form-label">@Model.bodyCommand.parameter_name2</label>
                            <input name="param2" , id="param2" , placeholder="@Model.bodyCommand.parameter_default_value2" , type="text" />

                        }
                        if (Model.bodyCommand.parameter_name3 != null)
                        {
                            <label for="param3" class="form-label">@Model.bodyCommand.parameter_name3</label>
                            <input name="param3" , id="param3" , placeholder="@Model.bodyCommand.parameter_default_value3" , type="text" />

             
                        }
                    }
                </div>
                <div class="btn-form">
                    <button style="background-color:#979797; width:150px;" class="form-button">Назад</button>
                    <input style="" class="form-button accept-btn" type="submit" id="send" value="Отправить" />
                </div>
            }

       
        </div>
    <div class="table-container">
        <table class="table">
            <thead>
                <tr>
                    <th>№</th>
                    <th>Дата и время</th>
                    <th>Команда</th>
                    <th>Параметр 1</th>
                    <th>Параметр 2</th>
                    <th>Параметр 3</th>
                    <th>Статус</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.histories.Reverse())
                {
                    <tr>
                        <td>@item.id</td>
                        <td>@item.dataTime</td>
                        <td>@item.command</td>
                        <td>@item.param1</td>
                        <td>@item.param2</td>
                        <td>@item.param3</td>
                        <td>@item.status</td>
                    </tr>
                }

            </tbody>
        </table>
    </div>
  

</body>
</html> 